OUTPUT_DIR: ./outputs/
DATA_ROOT: '../data'
DATASET_ABS: 'PHYRE'
PHYRE_PROTOCAL: 'template'
TEMPLATE: '1\_01\_01'
PHYRE_FOLD: 0
SOLVER:
  BASE_LR: 2.0e-4  # single GPU LR
  WEIGHT_DECAY: 3.0e-7
  SCHEDULER: 'cosine'
  MAX_ITERS: 800000
  VAL_INTERVAL: 5000
  WARMUP_ITERS: 1000
  BATCH_SIZE: 2 # single GPU Batch Size
INPUT:
  PRELOAD_TO_MEMORY: False
  IMAGE_CHANNEL: 1
RPIN:
  BACKBONE: 'hourglass_bn'
  ARCH: 'rpcin'
  VE_FEAT_DIM: 256
  IN_FEAT_DIM: 256
  # prediction setting:
  INPUT_SIZE: 1
  PRED_SIZE_TRAIN: 10
  PRED_SIZE_TEST: 10
  # input setting:
  INPUT_HEIGHT: 120
  INPUT_WIDTH: 160
  MAX_NUM_OBJS: 37
  # data augmentation
  HORIZONTAL_FLIP: False
  VERTICAL_FLIP: False
  # loss weight
  POSITION_LOSS_WEIGHT: 1
  # ----- RoIPooling Setting
  ROI_POOL_SIZE: 5
  ROI_POOL_SAMPLE_R: 2
  # ----- mask prediction
  MASK_LOSS_WEIGHT: 0.003
  MASK_SIZE: 21
  # ----- Architecture
  N_EXTRA_ROI_F: 2
  N_EXTRA_PRED_F: 0
  N_EXTRA_SELFD_F: 0
  N_EXTRA_RELD_F: 0
  N_EXTRA_AFFECTOR_F: 0
  N_EXTRA_AGGREGATOR_F: 0
  EXTRA_F_KERNEL: 3
  EXTRA_F_PADDING: 1
  IMAGE_EXT: '.npy'
  SEQ_CLS_LOSS_WEIGHT: 1.5
